import day6 from './index';

describe('On Day 6', () =>{
    it(`part1 is identity function`, ()=>{
        expect(day6.solveForPartOne(`....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...`)).toBe('41');
    });
    it(`part2 is identity function`, ()=>{
      expect(day6.solveForPartTwo(`....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...`)).toBe('6');
expect(day6.solveForPartTwo(`.##..
....#
.....
.^.#.
.....`)).toBe('1');
  })
});